---EXPLICIT TRANSACTION 

BEGIN  TRANSACTION 

   SELECT * FROM  COURSE

   INSERT INTO  COURSE  VALUES(8,'DB2','HYD',50,10000,'SQL TRAINING')

   SELECT * FROM  COURSE

   DELETE FROM COURSE  WHERE  CID = 2

   SELECT * FROM COURSE

   ROLLBACK  TRANSACTION

   SELECT * FROM  COURSE
   
   
   
  deleted record 2 and also inserted record 8 will be rollbacked as we are doing explicit TRANSACTION by using BEGIN TRANSACTION.
  
  
  

CONSTRAINTS cncept 

CREATE TABE CS4
	(
	
	ACID INT CNSTRAINT PK_ACID2 PRIMARY KEY,
	ACNAME VARCHAR(30) NOT NULL,
	ALOC CHAR(3) CNSTRAINT DF_ALOC2 DEFAULT 'BAN'
	BAL  DECIMAL(8,2) CNSTRAINT CK_BAL CHECK( BAL>500)
	AAID VARCHAR(10,2) CNSTRAINT AAIDCHCK UNIQUE -- not NULL, one null allowed   but use not null if you don't want null 
	
	
	)
	

ALTER TABLE CS4 ADD CONSTRAINT PK_ACID2 PRIMARY KEY

ALTER TABLE CS4 DROP PK_ACID2;
