SET SERVEROUTPUT ON;
DECLARE
   i HR.EMPLOYEES%ROWTYPE;
BEGIN
    SELECT * INTO i FROM HR.employees WHERE EMPLOYEE_ID = &EMPLOYEE_ID;
    DBMS_OUTPUT.PUT_LINE('eemp  '|| i.EMPLOYEE_ID || 'efirst  ' || i.FIRST_NAME);
END;
/